# Generated by Django 5.0.7 on 2024-07-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.CharField(max_length=250)),
                ('dep_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('classes', models.CharField(max_length=255)),
                ('fees', models.IntegerField()),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_names', to='schoolsystem.departmentmodel')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
